Introduce zokrates_mpc crate
Zokrates/ZoKrates pull request #1053
Opened 2021-11-23 14:39 UTC by dark64

Refactoring https://github.com/Zokrates/ZoKrates/tree/mpc

- [x] Introduce `zokrates_mpc` crate
- [ ] Support mpc in zokrates.js

2021-12-01 15:53 UTC, Schaeff requested changes
Nice! The core of the mpc logic would benefit from being maintained in a fork of the original implementation, for better attribution and tracking of the changes

2021-12-01 15:53 UTC, Schaeff commented on zokrates_book/src/toolbox/trusted_setup.md
> +Using the `-r` flag we pass a path of the file that contains parameters for our circuit with a depth of `2^n` (`phase1radix2m{n}`).
```suggestion
Using the `-r` flag, we pass a path to the file that contains the parameters for our circuit with depth `2^n` (`phase1radix2m{n}`).
```

2021-12-01 15:53 UTC, Schaeff commented on zokrates_book/src/toolbox/trusted_setup.md
> +The paramaters with various circuit depths can be computed using [phase2-bn254](https://github.com/kobigurk/phase2-bn254) utility by picking the latest response from [Perpetual Powers of Tau](https:/
```suggestion
The parameters for various circuit depths can be computed using [phase2-bn254](https://github.com/kobigurk/phase2-bn254) utility by picking the latest response from [Perpetual Powers of Tau](https://github.com/weijiekoh/perpetualpowersoftau) and following the instructions in the mentioned repositories.
```

2021-12-01 15:53 UTC, Schaeff commented on zokrates_cli/src/ops/mpc/export.rs
> +        MPCParameters::<<Bn128Field as BellmanFieldExtensions>::BellmanEngine>::read(reader, true)
Is it correct that the curve was checked to be bn128 before?

2021-12-01 15:53 UTC, Schaeff commented on zokrates_cli/src/ops/mpc/init.rs
> +    let mut radix_reader = BufReader::with_capacity(1024 * 1024, radix_file);
It is not clear to me what 1024 represents here. For more clarity, is would make sense to use an intermediate variable, or not pass a capacity.

2021-12-01 15:53 UTC, Schaeff commented on zokrates_cli/src/ops/mpc/verify.rs
> +                .help("Path to the radix file containing parameters for 2^n circuit depth (phase1radix2m{n})")
```suggestion
                .help("Path to the radix file containing parameters for a circuit depth of 2^n (phase1radix2m{n})")
```

2021-12-01 15:53 UTC, Schaeff commented on zokrates_cli/src/ops/mpc/verify.rs
> +    let mut radix_reader = BufReader::with_capacity(1024 * 1024, radix_file);
same

2021-12-02 17:31 UTC, dark64 commented on zokrates_cli/src/ops/mpc/init.rs
> +    let mut radix_reader = BufReader::with_capacity(1024 * 1024, radix_file);
This was done in the phase2 library originally, my assumption is most people will use one of the bigger radix files so a greater buffer capacity is used to speed up things (?)

2021-12-02 17:34 UTC, dark64 commented on zokrates_cli/src/ops/mpc/export.rs
> +        MPCParameters::<<Bn128Field as BellmanFieldExtensions>::BellmanEngine>::read(reader, true)
Not in the case of exporting because you can only initialize the ceremony for bn128 programs atm (this is checked for `init` command)

2021-12-02 18:16 UTC, merged