Run ark in wasm
Zokrates/ZoKrates pull request #1057
Opened 2021-11-25 19:08 UTC by dark64

https://github.com/Zokrates/ZoKrates/issues/1043

2021-11-29 09:57 UTC, dark64 commented on zokrates_core/src/ir/serialize.rs
> +            ProgEnum::Bls12_381Program(_) => Bls12_377Field::name(),
todo: this is wrong

2022-04-12 15:20 UTC, Schaeff requested changes
LGTM except that small typo!

2022-04-12 15:20 UTC, Schaeff commented on zokrates_cli/src/ops/verify.rs
> +        .default_value(zokrates_common::constants::BELLMAN)
Would it be acceptable to import `zokrates_common::constants`? This diff would be smaller and the code would be less verbose.

2022-04-12 15:20 UTC, Schaeff commented on zokrates_js/Cargo.toml
> +# [package.metadata.wasm-pack.profile.release]
Does this have to be included?

2022-04-12 15:20 UTC, Schaeff commented on zokrates_book/src/toolbox/zokrates_js.md
> +Performs the universal phase of a trusted setup. Only available for `marlin` scheme.
```suggestion
Performs the universal phase of a trusted setup. Only available for the `marlin` scheme.
```

2022-04-13 11:44 UTC, Schaeff approved these changes

2022-04-13 11:44 UTC, merged