Make return statement optional
Zokrates/ZoKrates pull request #1222
Opened 2022-08-29 13:22 UTC by dark64

Makes it possible to write the following 

```zokrates
def main() { 
    return; 
}
``` 

as `def main() {}`

2022-08-29 13:46 UTC, Schaeff requested changes

2022-08-29 13:46 UTC, Schaeff commented on zokrates_cli/examples/compile_errors/no_return.zok
> -def main() {
We should still have this test, just need to change the signature to one which requires a return statement.

2022-08-29 13:46 UTC, Schaeff commented on zokrates_core/src/semantics.rs
> +                            if tuple_type.elements.is_empty() =>
How about adding a method on `GTupleType` to make this less verbose? Or even on `GType`? `is_empty_tuple`? This could be used elsewhere also.
Also I suspect there's a way to remove `box` from the match arm without taking ownership? `match *&s.output` maybe?

2022-08-29 13:46 UTC, Schaeff commented on zokrates_core/src/semantics.rs
> +                            statements_checked.push(TypedStatement::Return(TypedExpression::Tuple(
Same here, `TypedExpression::empty_tuple()`

2022-08-29 14:26 UTC, dark64 commented on zokrates_core/src/semantics.rs
> +                            if tuple_type.elements.is_empty() =>
yep with `&*`

2022-08-29 14:26 UTC, dark64 commented on zokrates_cli/examples/compile_errors/no_return.zok
> -def main() {
true :+1:

2022-08-30 10:50 UTC, Schaeff commented on zokrates_book/src/language/functions.md
> +the signature. In this case, a return statement can be omitted.
```suggestion
If the return type of a function is the empty tuple `()`, the return type as well as the return statement can be omitted.
```

Then link to code like

```
def main() {
}
```

2022-08-30 12:29 UTC, Schaeff approved these changes

2022-08-30 12:29 UTC, merged