RNG tutorial
Zokrates/ZoKrates pull request #701
Opened 2020-11-11 11:41 UTC by qbzzt

This tutorial replaces the hash256 tutorial. It has several advantages:

1. Actual use case
2. More detailed explanations
3. Closing the loop by integrating with an Ethereum blockchain

2020-11-16 12:08 UTC, Schaeff requested changes

2020-11-16 12:08 UTC, Schaeff commented on zokrates_book/src/SUMMARY.md
> +- [Tutorial: Zero Knowledge Proofs for a Random Number Generator](rng_tutorial.md)
```suggestion
- [Tutorial: A zkSNARK RNG](rng_tutorial.md)
```

2020-11-16 12:38 UTC, qbzzt commented on zokrates_book/src/rng_tutorial.md
> +```
One of the things I'm trying to accomplish with my writing is to build a brand name. I can't put my name on the article, can I at least put it on the source code?

2020-11-16 13:25 UTC, qbzzt commented on zokrates_book/src/rng_tutorial.md
> +   ```
I believe it is. 

You know that verifyTx calls code that is functionally equivalent to what is on the command line. But a programmer who isn't part of the project, such as me, doesn't _know_ it. Blockchain development needs to be paranoid, so it is best to add this to help develop a bit more trust.

2020-11-16 14:20 UTC, Schaeff commented on zokrates_book/src/rng_tutorial.md
> +   ```
Didn't we check this proof with `verifyTx` on line 316? Am I right that we're flipping the bit twice and checking again here?

2020-11-16 23:29 UTC, qbzzt commented on zokrates_book/src/rng_tutorial.md
> +   ```
You're right. I'll remove it.

2020-11-17 00:02 UTC, qbzzt commented on zokrates_book/src/rng_tutorial.md
> +   zokrates compile -i reveal_bit.zok -o reveal_bit --light
Not necessary, but I believe it is a good idea to have binaries called by distinct names instead of `out`.

2020-11-17 00:03 UTC, qbzzt commented on zokrates_book/src/rng_tutorial.md
> +5. Next, Alice creates the `witness` file with the values of all the parameters in the program, and out of it generates a
I want to emphasize that `witness` is used in this step, but I'll rephrase.

2020-11-17 00:10 UTC, qbzzt commented on zokrates_book/src/rng_tutorial.md
> +```
Oh, you just mean the explanation. No problem, I'll do it.

2020-11-17 09:02 UTC, Schaeff commented on zokrates_book/src/rng_tutorial.md
> +   zokrates compile -i reveal_bit.zok -o reveal_bit --light
Oh right 👍

2020-11-20 11:11 UTC, Schaeff approved these changes

2020-11-20 11:12 UTC, merged