Textmate highlighter
Zokrates/ZoKrates pull request #773
Opened 2021-03-23 17:04 UTC by Schaeff

2021-03-24 15:49 UTC, dark64 requested changes
LGTM, just spotted a minor decimal suffix mistake for `field`

2021-03-24 15:49 UTC, dark64 commented on zokrates_parser/src/textmate/syntaxes/zokrates.tmLanguage.json
> +			"match": "\\b\\d[\\d_]*(u128|u16|u32|u64|u8|field)?\\b",
I think `field` should be just `f` here

2021-03-24 21:41 UTC, Schaeff commented
Failing because of some ark dependencies, will try again

2021-03-30 08:51 UTC, dark64 approved these changes

2021-03-30 09:09 UTC, merged