Support the use of constants in declaration types
Zokrates/ZoKrates pull request #864
Opened 2021-05-13 13:13 UTC by dark64

https://github.com/Zokrates/ZoKrates/issues/859

2021-05-14 15:01 UTC, Schaeff requested changes
Pretty clean implementation, a few suggestions.

2021-05-14 15:01 UTC, Schaeff commented on changelogs/unreleased/864-dark64
> +Support the use of constants in declaration types
declaration types are an internal concept, this should maybe mention struct and function declarations?

2021-05-14 15:01 UTC, Schaeff commented on zokrates_core/src/semantics.rs
> +        state: &mut State<'ast, T>,
Does this need to be a mutable reference?

2021-05-14 15:01 UTC, Schaeff commented on zokrates_core/src/semantics.rs
> +                .check_declaration_type(field.value.ty, module_id, state, &HashMap::new())
Generic struct types aren't in this PR then?

2021-05-14 15:01 UTC, Schaeff commented on zokrates_core/src/semantics.rs
> +        state: &mut State<'ast, T>,
And this?

2021-05-14 15:01 UTC, Schaeff commented on zokrates_core/src/semantics.rs
> +            if let Some((key, _)) = state
Getting key_value for a given key and then ignoring the value, isn't that just checking `contains`?

2021-05-14 15:01 UTC, Schaeff commented on zokrates_core/src/semantics.rs
> +                            Type::Uint(bitwidth) => Ok(Constant::Identifier(name, bitwidth.to_usize())),
This should only accept constants of bitwidth 32 for now. There should be a test for this similar to the one with field.
```suggestion
                            Type::Uint(UBitwidth::B32) => Ok(Constant::Identifier(name, bitwidth.to_usize())),
```

2021-05-14 15:01 UTC, Schaeff commented on zokrates_core/src/semantics.rs
> +                            _ => Err(ErrorInner {
This works but having `c` here makes it easier to see what `c` refers in this block

2021-05-14 15:01 UTC, Schaeff commented on zokrates_core/src/semantics.rs
> +        state: &mut State<'ast, T>,
Does this need to be mutable?

2021-05-14 15:01 UTC, Schaeff commented on zokrates_core/src/semantics.rs
> +                let res = self.check_for_loop(var, (from, to), statements, pos, module_id, state);
Does this technically need the whole state and not just the types, or is it for simplicity?

2021-05-14 15:01 UTC, Schaeff commented on zokrates_core/src/static_analysis/constant_inliner.rs
> +        let mut inliner = ConstantInliner {
using a constructor would be cleaner here

2021-05-14 15:01 UTC, Schaeff commented on zokrates_core/src/typed_absy/mod.rs
> +    pub ty: Type<'ast, T>,
Maybe I missed this before, but why do we need both a type and an expression here, where a type acan already be derived from the expression?

2021-05-14 15:01 UTC, Schaeff commented on zokrates_core/src/typed_absy/result_folder.rs
> +        Ok(s)
Why is this not visited?

2021-05-14 16:16 UTC, dark64 commented on zokrates_core/src/semantics.rs
> +                .check_declaration_type(field.value.ty, module_id, state, &HashMap::new())
No, that should be a separate pull request I think

2021-05-14 16:40 UTC, dark64 commented on zokrates_core/src/semantics.rs
> +            if let Some((key, _)) = state
I've refactored this a bit now, this was not clean I agree

2021-05-14 17:09 UTC, Schaeff commented on zokrates_core/src/semantics.rs
> +                .check_declaration_type(field.value.ty, module_id, state, &HashMap::new())
Yeah good, just making sure I'm following here!

2021-05-14 17:09 UTC, dark64 commented on zokrates_core/src/semantics.rs
> +                let res = self.check_for_loop(var, (from, to), statements, pos, module_id, state);
It was for simplicity, but after further examination, I guess there is no need to pass a whole state where it's not actually needed, will revert some of this

2021-05-14 17:12 UTC, dark64 commented on zokrates_core/src/typed_absy/mod.rs
> +    pub ty: Type<'ast, T>,
To avoid `Clone` trait bound, see discussion here https://github.com/Zokrates/ZoKrates/pull/792#discussion_r620493339

2021-05-14 17:13 UTC, dark64 commented on zokrates_core/src/semantics.rs
> +        state: &mut State<'ast, T>,
It was because of the `.or_default` on constants map entry, but I'm making some changes to remove the need for this mutability

2021-05-14 17:14 UTC, dark64 commented on zokrates_core/src/semantics.rs
> +        state: &mut State<'ast, T>,
It was because of the .or_default on constants map entry, but I'm making some changes to remove the need for this mutability

2021-05-14 17:14 UTC, dark64 commented on zokrates_core/src/semantics.rs
> +        state: &mut State<'ast, T>,
Same as other, will be removed

2021-05-14 17:16 UTC, dark64 commented on zokrates_core/src/semantics.rs
> +                            Type::Uint(bitwidth) => Ok(Constant::Identifier(name, bitwidth.to_usize())),
I was doing a bit of future-proofing here, but I agree this arm should check only for 32 now

2021-05-14 17:22 UTC, dark64 commented on zokrates_core/src/typed_absy/result_folder.rs
> +        Ok(s)
whoops :facepalm:

2021-05-14 19:36 UTC, Schaeff commented on zokrates_core/src/typed_absy/mod.rs
> +    pub ty: Type<'ast, T>,
Oh right, forgot about that

2021-05-16 21:28 UTC, Schaeff approved these changes

2021-05-16 21:29 UTC, merged